# Generated by Django 3.2.18 on 2023-03-10 17:55

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_date', models.DateField(verbose_name='Expiration Date')),
                ('holder', models.CharField(max_length=50, verbose_name='Card Holder')),
                ('number', django_cryptography.fields.encrypt(models.CharField(max_length=255, verbose_name='Card Number'))),
                ('cvv', models.IntegerField(blank=True, null=True, verbose_name='CVV')),
                ('brand', models.CharField(blank=True, max_length=12, null=True, verbose_name='Card Brand')),
            ],
        ),
    ]
