# Generated by Django 3.2.18 on 2023-03-10 17:45

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0002_auto_20230310_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255, verbose_name='Card Number')),
        ),
    ]
